services:
  mysql:
    image: 'mysql:latest'
    environment:
      - "MYSQL_DATABASE=deal"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - '3307:3306'

  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3307/deal?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

volumes:
  mysql-data:
